### ISSUE TITLE
Make variable names idomatic

### ISSUE THREAD

**Issue by yeboahnanaosei** [ahmednafies/go-covid#13]
In go, it is valid to use underscores to begin variable names but this is rarely done. I think it will be more idiomatic to remove the use of underscores at the beginning of some of the variables.

Is there any special reason for using the underscores?

Here is an example of such a variable:
https://github.com/ahmednafies/go-covid/blob/aa91f503ed4f6541a983c99af54d5a0526c3d2e9/covid/covid.go#L56

**Comment by nf1s** [comment]
@yeboahnanaosei , there is no special reason apart from that I come from python background 😆

**Comment by yeboahnanaosei** [comment]
I suspected that exact reason. Lol
