### ISSUE TITLE
Switch to Go modules instead of dep?

### ISSUE THREAD

**Issue by yeboahnanaosei** [ahmednafies/go-covid#7]
Hi, first of all, I want to appreciate you for putting this together. I have myself built a website that serves data on the current coronavirus pandemic. So I'm glad there is a native package built in go.

I noticed you are using dep to manage your dependencies. I have not used dep before I only used the built in go modules which solves the same problem.

I was thinking that it might be good to use go modules instead of dep since its built directly into go and it is more like the "official" way to handle dependencies now.

dep was really useful when go modules were not around. But now go modules have come to solve the exact problem natively

**Comment by nf1s** [comment]
sounds like a great idea, I will do that :)
thank you so much for the hint 🙏

**Comment by yeboahnanaosei** [comment]
Here is a link to an authoritative source on go modules just in case you need it:
<a href="https://github.com/golang/go/wiki/Modules" target="_blank" title="Go modules">https://github.com/golang/go/wiki/Modules</a>

**Comment by nf1s** [comment]
issue resolved :)
